//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorQitService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string industry { get; set; }
        public string specialities { get; set; }
        public string positions { get; set; }
        public string interests { get; set; }
        public string languages { get; set; }
        public string skills { get; set; }
        public string educations { get; set; }
        public string volunteer { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string location { get; set; }
        public Nullable<int> hours { get; set; }
        public string username { get; set; }
        public string passwod { get; set; }
        public string email { get; set; }
    
        public virtual VacancyEmployee VacancyEmployee { get; set; }
    }
}
